### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by philgresh** [philgresh/signdocs#2]
# PA Review: User Auth
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

## Functionality

- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] If logged in, should not be able to visit `/login` or `/signup`
- [x] If logged in, should be able to refresh the page and still be logged in
- [x] Demo user can log in
- [x] Demo user can log out

**Comment by Vanchen07** [comment]
If I tried to sign in with an error, the errors render, but if I switch to signup, the errors from sign don't clear out. They remain on the form when I'm at sign up.

**Comment by philgresh** [comment]
Resolved with [this commit ](https://github.com/philgresh/signdocs/commit/b5f5d0c46a78d027944fc03a77777e93492fc351)!

**Comment by Vanchen07** [comment]
Thanks for the changes, looks good!
