### ISSUE TITLE
Uploaded PDF, but I saw another PDF instead

### ISSUE THREAD

**Issue by 949mac** [philgresh/signdocs#50]
Hello -

I made a few attempts earlier today, but the PDFs I uploaded were not rendering. Instead, I may have seen someone else's uploaded PDF.

Here's an example: https://signdocs.herokuapp.com/#/documents/7643a4d1-9291-40a0-bab9-957069f01647/prepare

After trying again just now, my PDFs appear to be uploading fine. But it appears there is some issue w/ a newly uploaded file taking precedence.

**Comment by philgresh** [comment]
Hi Mike, I appreciate you reaching out. This project has been stale for awhile, I'm familiar with the bug but haven't had time to sort it out. If you're feeling investigative, I'd invite you to fork the repo and attempt a fix!
